//! proptest scaffolding for `app.toplevel` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_all_dispatched
    // generator: scripted events of each type
    // predicate: the handler is called once per event
    #[test]
    fn p_all_dispatched() {
        todo_predicate!("the handler is called once per event");
    }
}

proptest! {
    // id: p_global_move
    // generator: a view with no hover
    // predicate: has-mouse-move-global is true
    #[test]
    fn p_global_move() {
        todo_predicate!("has-mouse-move-global is true");
    }
}

proptest! {
    // id: p_start_scroll
    // generator: two nested start-scroll intents
    // predicate: scroll-state holds the last one and the position
    #[test]
    fn p_start_scroll() {
        todo_predicate!("scroll-state holds the last one and the position");
    }
}

proptest! {
    // id: p_start_replaced
    // generator: start-scroll amid other intents
    // predicate: order is kept and no start-scroll intent survives
    #[test]
    fn p_start_replaced() {
        todo_predicate!("order is kept and no start-scroll intent survives");
    }
}

proptest! {
    // id: p_scroll_drag
    // generator: move from [0, 0] to [3, 7]
    // predicate: the function receives [3, 7]
    #[test]
    fn p_scroll_drag() {
        todo_predicate!("the function receives [3, 7]");
    }
}

proptest! {
    // id: p_scroll_release
    // generator: mouse-up in a drag
    // predicate: the only effect is set scroll-state to nil
    #[test]
    fn p_scroll_release() {
        todo_predicate!("the only effect is set scroll-state to nil");
    }
}

proptest! {
    // id: p_click_away
    // generator: click on empty space with focus set
    // predicate: the effect sets focus to nil
    #[test]
    fn p_click_away() {
        todo_predicate!("the effect sets focus to nil");
    }
}

proptest! {
    // id: p_focus_kept
    // generator: click on a handler with focus set
    // predicate: focus is untouched
    #[test]
    fn p_focus_kept() {
        todo_predicate!("focus is untouched");
    }
}

proptest! {
    // id: p_namespaces
    // generator: app state with user keys
    // predicate: reserved keys never collide with user keys
    #[test]
    fn p_namespaces() {
        todo_predicate!("reserved keys never collide with user keys");
    }
}

proptest! {
    // id: p_initial
    // generator: make-app with no state
    // predicate: state equals an empty map
    #[test]
    fn p_initial() {
        todo_predicate!("state equals an empty map");
    }
}

proptest! {
    // id: p_drag_effect
    // generator: a scrollbar press
    // predicate: the set scroll-state effect is emitted
    #[test]
    fn p_drag_effect() {
        todo_predicate!("the set scroll-state effect is emitted");
    }
}

proptest! {
    // id: p_focus_effect
    // generator: click-away
    // predicate: the set focus nil effect is emitted
    #[test]
    fn p_focus_effect() {
        todo_predicate!("the set focus nil effect is emitted");
    }
}

