---- MODULE apptoplevel ----
\* Generated by `spk compile` from spec `app.toplevel` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"idle", "scrolling", "focus_held", "focus_cleared"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "idle"

Next ==
  \* t_start_scroll: idle -> scrolling (guard: [[app.toplevel.start_scroll_intercept]])
  \/ vpc = "idle" /\ vpc' = "scrolling"
  \* t_end_scroll: scrolling -> idle (guard: [[app.toplevel.scroll_release]])
  \/ vpc = "scrolling" /\ vpc' = "idle"
  \* t_take_focus: idle -> focus_held (guard: [[app.toplevel.focus_kept_on_hit]])
  \/ vpc = "idle" /\ vpc' = "focus_held"
  \* t_blur: focus_held -> focus_cleared (guard: [[app.toplevel.click_away_blurs]])
  \/ vpc = "focus_held" /\ vpc' = "focus_cleared"
  \* t_reset: focus_cleared -> idle (guard: [[app.toplevel.initial_state_default]])
  \/ vpc = "focus_cleared" /\ vpc' = "idle"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"focus_cleared" :> "on click-away the root emits a set of focus to nil"

============================================================================
