//! proptest scaffolding for `backend.render` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_contract
// generator: all three backends
// predicate: each exposes draw, measureText, indexForPosition, copyToClipboard and subscribe
#[test]
fn p_contract() {
        todo_predicate!("each exposes draw, measureText, indexForPosition, copyToClipboard and subscribe");
}

// id: p_primitives
// generator: one node of each primitive and an unknown node
// predicate: each draws and the unknown node draws its children
#[test]
fn p_primitives() {
        todo_predicate!("each draws and the unknown node draws its children");
}

// id: p_determinism
// generator: random views
// predicate: two draws produce equal pixels
#[test]
fn p_determinism() {
        todo_predicate!("two draws produce equal pixels");
}

// id: p_stack
// generator: random nested views
// predicate: stack depth is 0 after draw
#[test]
fn p_stack() {
        todo_predicate!("stack depth is 0 after draw");
}

// id: p_index
// generator: text hello at x from -5 to 200
// predicate: index is 0 at the left, 5 at the right and never decreases
#[test]
fn p_index() {
        todo_predicate!("index is 0 at the left, 5 at the right and never decreases");
}

// id: p_clipboard
// generator: copy hello and a paste event
// predicate: the clipboard gets hello and the paste arrives as a string
#[test]
fn p_clipboard() {
        todo_predicate!("the clipboard gets hello and the paste arrives as a string");
}

// id: p_headless
// generator: the todo-app initial state in a runtime with no DOM
// predicate: an image of non-zero size is produced
#[test]
fn p_headless() {
        todo_predicate!("an image of non-zero size is produced");
}

// id: p_dpr
// generator: dpr in 1, 2, 3
// predicate: backing size equals css size times dpr
#[test]
fn p_dpr() {
        todo_predicate!("backing size equals css size times dpr");
}

// id: p_resize
// generator: random viewport sizes
// predicate: a redraw follows each resize with the new size in context
#[test]
fn p_resize() {
        todo_predicate!("a redraw follows each resize with the new size in context");
}

// id: p_input
// generator: scripted pointer events
// predicate: the router receives view-space coordinates
#[test]
fn p_input() {
        todo_predicate!("the router receives view-space coordinates");
}

// id: p_keys
// generator: a, A, Enter, Backspace, ArrowLeft, Shift
// predicate: a, A, enter, backspace, left and nothing
#[test]
fn p_keys() {
        todo_predicate!("a, A, enter, backspace, left and nothing");
}

// id: p_touch_action
// generator: mounted canvas
// predicate: computed touch-action is none
#[test]
fn p_touch_action() {
        todo_predicate!("computed touch-action is none");
}

// id: p_raf
// generator: N requests per frame
// predicate: one draw per frame
#[test]
fn p_raf() {
        todo_predicate!("one draw per frame");
}

// id: p_swappable
// generator: counter-counter on each backend
// predicate: the same click yields the same effect list
#[test]
fn p_swappable() {
        todo_predicate!("the same click yields the same effect list");
}

// id: p_text_metrics
// generator: text backend
// predicate: a label of 5 characters measures 5 by 1
#[test]
fn p_text_metrics() {
        todo_predicate!("a label of 5 characters measures 5 by 1");
}

// id: p_a11y
// generator: views with buttons
// predicate: one accessible node per interactive node
#[test]
fn p_a11y() {
        todo_predicate!("one accessible node per interactive node");
}

// id: p_safe_area
// generator: simulated insets
// predicate: content stays inside the insets
#[test]
fn p_safe_area() {
        todo_predicate!("content stays inside the insets");
}

