---- MODULE backendrender ----
\* Generated by `spk compile` from spec `backend.render` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"detached", "attached", "drawing"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "detached"

Next ==
  \* t_attach: detached -> attached (guard: [[backend.render.input_forwarded]])
  \/ vpc = "detached" /\ vpc' = "attached"
  \* t_draw: attached -> drawing (guard: [[backend.render.raf_coalesced]])
  \/ vpc = "attached" /\ vpc' = "drawing"
  \* t_drawn: drawing -> attached (guard: [[backend.render.transform_stack_balanced]])
  \/ vpc = "drawing" /\ vpc' = "attached"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
