//! proptest scaffolding for `components.scrollview` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_default
// generator: no offset prop
// predicate: offset equals [0, 0]
#[test]
fn p_default() {
        todo_predicate!("offset equals [0, 0]");
}

// id: p_translate
// generator: random offsets
// predicate: body origin equals the negated offset
#[test]
fn p_translate() {
        todo_predicate!("body origin equals the negated offset");
}

// id: p_range
// generator: viewport 200 over content 500 and 100
// predicate: max offset is 300 and 0
#[test]
fn p_range() {
        todo_predicate!("max offset is 300 and 0");
}

// id: p_wheel_child
// generator: a child that handles scroll
// predicate: the child's intents are returned
#[test]
fn p_wheel_child() {
        todo_predicate!("the child's intents are returned");
}

// id: p_wheel
// generator: offset 0 and delta 50, offset at max and delta 50
// predicate: first updates to 50, second returns nothing
#[test]
fn p_wheel() {
        todo_predicate!("first updates to 50, second returns nothing");
}

// id: p_stale
// generator: stored offset above max then a small scroll
// predicate: render keeps it, the update clamps it
#[test]
fn p_stale() {
        todo_predicate!("render keeps it, the update clamps it");
}

// id: p_bars
// generator: content larger on one axis only
// predicate: exactly one bar is present at the right place
#[test]
fn p_bars() {
        todo_predicate!("exactly one bar is present at the right place");
}

// id: p_thumb
// generator: total 500 view 200 offset 100
// predicate: thumb spans 0.2 to 0.6 of the track
#[test]
fn p_thumb() {
        todo_predicate!("thumb spans 0.2 to 0.6 of the track");
}

// id: p_bar_drag
// generator: press then delta
// predicate: the function returns the set offset effect
#[test]
fn p_bar_drag() {
        todo_predicate!("the function returns the set offset effect");
}

// id: p_div0
// generator: viewport 0
// predicate: offset is 0 and finite
#[test]
fn p_div0() {
        todo_predicate!("offset is 0 and finite");
}

// id: p_clip
// generator: pointer outside the viewport over clipped content
// predicate: no intents
#[test]
fn p_clip() {
        todo_predicate!("no intents");
}

// id: p_touch_scroll
// generator: touch drag of 30 px
// predicate: offset changes by 30 within range
#[test]
fn p_touch_scroll() {
        todo_predicate!("offset changes by 30 within range");
}

// id: p_momentum
// generator: flick then rest
// predicate: offset keeps changing then settles, and is static under reduced motion
#[test]
fn p_momentum() {
        todo_predicate!("offset keeps changing then settles, and is static under reduced motion");
}

