---- MODULE componentshover ----
\* Generated by `spk compile` from spec `components.hover` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"not_hovered", "hovered"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "not_hovered"

Next ==
  \* t_enter: not_hovered -> hovered (guard: [[components.hover.hover_enter]])
  \/ vpc = "not_hovered" /\ vpc' = "hovered"
  \* t_leave: hovered -> not_hovered (guard: [[components.hover.hover_leave]])
  \/ vpc = "hovered" /\ vpc' = "not_hovered"
  \* t_stay: hovered -> hovered (guard: [[components.hover.hover_stays_inside]])
  \/ vpc = "hovered" /\ vpc' = "hovered"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
