//! proptest scaffolding for `components.scrollview` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_default
    // generator: no offset prop
    // predicate: offset equals [0, 0]
    #[test]
    fn p_default() {
        todo_predicate!("offset equals [0, 0]");
    }
}

proptest! {
    // id: p_translate
    // generator: random offsets
    // predicate: body origin equals the negated offset
    #[test]
    fn p_translate() {
        todo_predicate!("body origin equals the negated offset");
    }
}

proptest! {
    // id: p_range
    // generator: viewport 200 over content 500 and 100
    // predicate: max offset is 300 and 0
    #[test]
    fn p_range() {
        todo_predicate!("max offset is 300 and 0");
    }
}

proptest! {
    // id: p_wheel_child
    // generator: a child that handles scroll
    // predicate: the child's intents are returned
    #[test]
    fn p_wheel_child() {
        todo_predicate!("the child's intents are returned");
    }
}

proptest! {
    // id: p_wheel
    // generator: offset 0 and delta 50, offset at max and delta 50
    // predicate: first updates to 50, second returns nothing
    #[test]
    fn p_wheel() {
        todo_predicate!("first updates to 50, second returns nothing");
    }
}

proptest! {
    // id: p_stale
    // generator: stored offset above max then a small scroll
    // predicate: render keeps it, the update clamps it
    #[test]
    fn p_stale() {
        todo_predicate!("render keeps it, the update clamps it");
    }
}

proptest! {
    // id: p_bars
    // generator: content larger on one axis only
    // predicate: exactly one bar is present at the right place
    #[test]
    fn p_bars() {
        todo_predicate!("exactly one bar is present at the right place");
    }
}

proptest! {
    // id: p_thumb
    // generator: total 500 view 200 offset 100
    // predicate: thumb spans 0.2 to 0.6 of the track
    #[test]
    fn p_thumb() {
        todo_predicate!("thumb spans 0.2 to 0.6 of the track");
    }
}

proptest! {
    // id: p_bar_drag
    // generator: press then delta
    // predicate: the function returns the set offset effect
    #[test]
    fn p_bar_drag() {
        todo_predicate!("the function returns the set offset effect");
    }
}

proptest! {
    // id: p_div0
    // generator: viewport 0
    // predicate: offset is 0 and finite
    #[test]
    fn p_div0() {
        todo_predicate!("offset is 0 and finite");
    }
}

proptest! {
    // id: p_clip
    // generator: pointer outside the viewport over clipped content
    // predicate: no intents
    #[test]
    fn p_clip() {
        todo_predicate!("no intents");
    }
}

proptest! {
    // id: p_touch_scroll
    // generator: touch drag of 30 px
    // predicate: offset changes by 30 within range
    #[test]
    fn p_touch_scroll() {
        todo_predicate!("offset changes by 30 within range");
    }
}

proptest! {
    // id: p_momentum
    // generator: flick then rest
    // predicate: offset keeps changing then settles, and is static under reduced motion
    #[test]
    fn p_momentum() {
        todo_predicate!("offset keeps changing then settles, and is static under reduced motion");
    }
}

