---- MODULE componentmodel ----
\* Generated by `spk compile` from spec `component.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"declared", "rendered", "cached"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "declared"

Next ==
  \* t_render: declared -> rendered (guard: [[component.model.render_pure]])
  \/ vpc = "declared" /\ vpc' = "rendered"
  \* t_cache: rendered -> cached (guard: [[component.model.path_resolves]])
  \/ vpc = "rendered" /\ vpc' = "cached"
  \* t_redefine: cached -> declared (guard: [[component.model.single_map_arg]])
  \/ vpc = "cached" /\ vpc' = "declared"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
