//! proptest scaffolding for `components.textarea` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_focus_path
    // generator: two textareas with different text paths
    // predicate: requesting focus on one leaves the other unfocused
    #[test]
    fn p_focus_path() {
        todo_predicate!("requesting focus on one leaves the other unfocused");
    }
}

proptest! {
    // id: p_request_focus
    // generator: click inside and on empty space
    // predicate: inside returns request-focus first, empty returns nothing
    #[test]
    fn p_request_focus() {
        todo_predicate!("inside returns request-focus first, empty returns nothing");
    }
}

proptest! {
    // id: p_keys_focus
    // generator: key events while unfocused
    // predicate: no effects
    #[test]
    fn p_keys_focus() {
        todo_predicate!("no effects");
    }
}

proptest! {
    // id: p_key_map
    // generator: each named key and the string s
    // predicate: each yields its effect and others yield none
    #[test]
    fn p_key_map() {
        todo_predicate!("each yields its effect and others yield none");
    }
}

proptest! {
    // id: p_insert
    // generator: text hello cursor 2 s XY and nil text
    // predicate: hello becomes heXYllo cursor 4, and nil gives XY
    #[test]
    fn p_insert() {
        todo_predicate!("hello becomes heXYllo cursor 4, and nil gives XY");
    }
}

proptest! {
    // id: p_insert_sel
    // generator: text hello cursor 4 select-cursor 1 s Z
    // predicate: text becomes hZo cursor 2 selection nil
    #[test]
    fn p_insert_sel() {
        todo_predicate!("text becomes hZo cursor 2 selection nil");
    }
}

proptest! {
    // id: p_delete
    // generator: cursor 0, cursor 3 and a selection
    // predicate: no change at 0, one char removed at 3, range removed with a selection
    #[test]
    fn p_delete() {
        todo_predicate!("no change at 0, one char removed at 3, range removed with a selection");
    }
}

proptest! {
    // id: p_cursor
    // generator: random moves
    // predicate: 0 <= cursor <= len(text)
    #[test]
    fn p_cursor() {
        todo_predicate!("0 <= cursor <= len(text)");
    }
}

proptest! {
    // id: p_prev_line
    // generator: text ab newline cd with cursor 4
    // predicate: cursor becomes 2 and the selection is cleared
    #[test]
    fn p_prev_line() {
        todo_predicate!("cursor becomes 2 and the selection is cleared");
    }
}

proptest! {
    // id: p_next_line
    // generator: the same text with cursor 0 and cursor 4
    // predicate: cursor becomes 3 then 5
    #[test]
    fn p_next_line() {
        todo_predicate!("cursor becomes 3 then 5");
    }
}

proptest! {
    // id: p_down_cursor
    // generator: click at a known glyph
    // predicate: cursor, mpos and down-pos are set and selection is nil
    #[test]
    fn p_down_cursor() {
        todo_predicate!("cursor, mpos and down-pos are set and selection is nil");
    }
}

proptest! {
    // id: p_drag
    // generator: move with and without down-pos
    // predicate: mpos is set only with down-pos
    #[test]
    fn p_drag() {
        todo_predicate!("mpos is set only with down-pos");
    }
}

proptest! {
    // id: p_finish_drag
    // generator: drag from index 1 to index 4
    // predicate: selection and cursor follow the rule and down-pos is nil
    #[test]
    fn p_finish_drag() {
        todo_predicate!("selection and cursor follow the rule and down-pos is nil");
    }
}

proptest! {
    // id: p_double_click
    // generator: two clicks 200 ms apart then 600 ms apart
    // predicate: the first pair selects a word and the second does not
    #[test]
    fn p_double_click() {
        todo_predicate!("the first pair selects a word and the second does not");
    }
}

proptest! {
    // id: p_copy
    // generator: selected and unselected
    // predicate: text range or nothing
    #[test]
    fn p_copy() {
        todo_predicate!("text range or nothing");
    }
}

proptest! {
    // id: p_cut
    // generator: selection 1 to 3 in hello
    // predicate: text becomes hlo and the clipboard gets el
    #[test]
    fn p_cut() {
        todo_predicate!("text becomes hlo and the clipboard gets el");
    }
}

proptest! {
    // id: p_paste
    // generator: paste focused and unfocused
    // predicate: insert-text or nothing
    #[test]
    fn p_paste() {
        todo_predicate!("insert-text or nothing");
    }
}

proptest! {
    // id: p_state_split
    // generator: editing and moving
    // predicate: text paths point into app state and cursor paths into extra
    #[test]
    fn p_state_split() {
        todo_predicate!("text paths point into app state and cursor paths into extra");
    }
}

proptest! {
    // id: p_border
    // generator: both variants
    // predicate: bordered view is larger by 10 by 4 than its body and light has no stroke
    #[test]
    fn p_border() {
        todo_predicate!("bordered view is larger by 10 by 4 than its body and light has no stroke");
    }
}

proptest! {
    // id: p_selection_drawn
    // generator: selection present and focused
    // predicate: highlight and cursor nodes exist
    #[test]
    fn p_selection_drawn() {
        todo_predicate!("highlight and cursor nodes exist");
    }
}

proptest! {
    // id: p_enter
    // generator: enter while focused
    // predicate: the insert-newline effect is returned so it can be replaced
    #[test]
    fn p_enter() {
        todo_predicate!("the insert-newline effect is returned so it can be replaced");
    }
}

proptest! {
    // id: p_ime
    // generator: composition events
    // predicate: one insert-text at the end
    #[test]
    fn p_ime() {
        todo_predicate!("one insert-text at the end");
    }
}

