---- MODULE componentstextarea ----
\* Generated by `spk compile` from spec `components.textarea` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"unfocused", "focused", "selecting", "selected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unfocused"

Next ==
  \* t_focus: unfocused -> focused (guard: [[components.textarea.request_focus_on_hit]])
  \/ vpc = "unfocused" /\ vpc' = "focused"
  \* t_drag_start: focused -> selecting (guard: [[components.textarea.pointer_down_cursor]])
  \/ vpc = "focused" /\ vpc' = "selecting"
  \* t_drag_end: selecting -> selected (guard: [[components.textarea.finish_drag_rule]])
  \/ vpc = "selecting" /\ vpc' = "selected"
  \* t_edit_selected: selected -> focused (guard: [[components.textarea.insert_replaces_selection]])
  \/ vpc = "selected" /\ vpc' = "focused"
  \* t_move: selected -> focused (guard: [[components.textarea.cursor_clamped]])
  \/ vpc = "selected" /\ vpc' = "focused"
  \* t_blur: focused -> unfocused (guard: [[app.toplevel.click_away_blurs]])
  \/ vpc = "focused" /\ vpc' = "unfocused"
  \* t_blur_selected: selected -> unfocused (guard: [[app.toplevel.click_away_blurs]])
  \/ vpc = "selected" /\ vpc' = "unfocused"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
