//! proptest scaffolding for `components.pinned_panel` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_contextual_source
// generator: `panel nested under a scrollview with context.scroll set`
// predicate: offset value equals `context.scroll`, never a call-site literal
#[test]
fn p_contextual_source() {
        todo_predicate!("offset value equals `context.scroll`, never a call-site literal");
}

// id: p_activation
// generator: `offset swept across and beyond the range`
// predicate: active exactly on `[start, end]`, inactive outside it
#[test]
fn p_activation() {
        todo_predicate!("active exactly on `[start, end]`, inactive outside it");
}

// id: p_fixed_position
// generator: `offset swept while active`
// predicate: body's screen position is constant across every sampled offset
#[test]
fn p_fixed_position() {
        todo_predicate!("body's screen position is constant across every sampled offset");
}

// id: p_spacer_constant
// generator: `panel toggled active and inactive`
// predicate: total scrollview content height is unchanged by activation state
#[test]
fn p_spacer_constant() {
        todo_predicate!("total scrollview content height is unchanged by activation state");
}

// id: p_no_jump
// generator: `offset stepped across activation-range.end`
// predicate: screen position immediately before and after the step are equal
#[test]
fn p_no_jump() {
        todo_predicate!("screen position immediately before and after the step are equal");
}

// id: p_nested_priority
// generator: `two overlapping panels, no z prop`
// predicate: the later-in-tree panel paints on top
#[test]
fn p_nested_priority() {
        todo_predicate!("the later-in-tree panel paints on top");
}

// id: p_pure
// generator: `same offset supplied twice`
// predicate: identical output view value both times
#[test]
fn p_pure() {
        todo_predicate!("identical output view value both times");
}

