//! proptest scaffolding for `components.numeric` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_default
// generator: no num
// predicate: num is 0
#[test]
fn p_default() {
        todo_predicate!("num is 0");
}

// id: p_dec
// generator: num 3 with min 3 and num 3 with no min
// predicate: stays 3 then becomes 2
#[test]
fn p_dec() {
        todo_predicate!("stays 3 then becomes 2");
}

// id: p_inc
// generator: num 3 with max 3 and no max
// predicate: stays 3 then becomes 4
#[test]
fn p_inc() {
        todo_predicate!("stays 3 then becomes 4");
}

// id: p_label_width
// generator: labels 1 and 12345
// predicate: centred area is at least 20
#[test]
fn p_label_width() {
        todo_predicate!("centred area is at least 20");
}

// id: p_buttons
// generator: click minus and plus
// predicate: dec and inc effects carry path and limit
#[test]
fn p_buttons() {
        todo_predicate!("dec and inc effects carry path and limit");
}

// id: p_mapping
// generator: min 5 max 20 width 300 integer at x 150, x -10, x 400
// predicate: 12, 5 and 20
#[test]
fn p_mapping() {
        todo_predicate!("12, 5 and 20");
}

// id: p_gesture
// generator: move before down and after down
// predicate: only the second updates
#[test]
fn p_gesture() {
        todo_predicate!("only the second updates");
}

// id: p_label
// generator: num 3 and 3.14159
// predicate: 3 and 3.14
#[test]
fn p_label() {
        todo_predicate!("3 and 3.14");
}

// id: p_fill
// generator: num 3 min 0 max 20 width 100
// predicate: width is 15
#[test]
fn p_fill() {
        todo_predicate!("width is 15");
}

// id: p_max_width
// generator: no max-width
// predicate: 100
#[test]
fn p_max_width() {
        todo_predicate!("100");
}

// id: p_capture
// generator: drag outside bounds on touch
// predicate: updates continue until release
#[test]
fn p_capture() {
        todo_predicate!("updates continue until release");
}

