//! proptest scaffolding for `components.select` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_header_toggle
// generator: open? false then true
// predicate: the effect flips open?
#[test]
fn p_header_toggle() {
        todo_predicate!("the effect flips open?");
}

// id: p_header_label
// generator: options this, that, the-other and selected that
// predicate: label is That, and with nil it is no selection
#[test]
fn p_header_label() {
        todo_predicate!("label is That, and with nil it is no selection");
}

// id: p_list_open
// generator: open? both values
// predicate: list nodes exist only when open
#[test]
fn p_list_open() {
        todo_predicate!("list nodes exist only when open");
}

// id: p_row_effect
// generator: click second row
// predicate: effect is select with the selected path and that
#[test]
fn p_row_effect() {
        todo_predicate!("effect is select with the selected path and that");
}

// id: p_select_closes
// generator: a select intent
// predicate: output is select then set open? false
#[test]
fn p_select_closes() {
        todo_predicate!("output is select then set open? false");
}

// id: p_select_sets
// generator: select then read
// predicate: the selected path holds the value
#[test]
fn p_select_sets() {
        todo_predicate!("the selected path holds the value");
}

// id: p_row_visuals
// generator: selected and hovered rows
// predicate: fills and label colors match
#[test]
fn p_row_visuals() {
        todo_predicate!("fills and label colors match");
}

// id: p_geometry
// generator: labels of three widths
// predicate: row width equals max plus 24
#[test]
fn p_geometry() {
        todo_predicate!("row width equals max plus 24");
}

// id: p_row_hover
// generator: hover two different rows
// predicate: two distinct extra keys
#[test]
fn p_row_hover() {
        todo_predicate!("two distinct extra keys");
}

// id: p_touch_rows
// generator: touch device
// predicate: row height is at least 44
#[test]
fn p_touch_rows() {
        todo_predicate!("row height is at least 44");
}

