---- MODULE componentsnumeric ----
\* Generated by `spk compile` from spec `components.numeric` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"idle", "adjusting"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "idle"

Next ==
  \* t_press: idle -> adjusting (guard: [[components.numeric.slider_gesture]])
  \/ vpc = "idle" /\ vpc' = "adjusting"
  \* t_release: adjusting -> idle (guard: [[components.numeric.slider_mapping]])
  \/ vpc = "adjusting" /\ vpc' = "idle"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
