---- MODULE componentsscrollview ----
\* Generated by `spk compile` from spec `components.scrollview` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"at_top", "scrolled", "dragging_bar"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "at_top"

Next ==
  \* t_scroll: at_top -> scrolled (guard: [[components.scrollview.wheel_updates_offset]])
  \/ vpc = "at_top" /\ vpc' = "scrolled"
  \* t_back: scrolled -> at_top (guard: [[components.scrollview.range_formula]])
  \/ vpc = "scrolled" /\ vpc' = "at_top"
  \* t_grab: scrolled -> dragging_bar (guard: [[components.scrollview.bar_drag]])
  \/ vpc = "scrolled" /\ vpc' = "dragging_bar"
  \* t_release: dragging_bar -> scrolled (guard: [[components.scrollview.div0_safe]])
  \/ vpc = "dragging_bar" /\ vpc' = "scrolled"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
