---- MODULE componentsselect ----
\* Generated by `spk compile` from spec `components.select` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"closed", "open"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "closed"

Next ==
  \* t_open: closed -> open (guard: [[components.select.header_toggles]])
  \/ vpc = "closed" /\ vpc' = "open"
  \* t_choose: open -> closed (guard: [[components.select.select_closes]])
  \/ vpc = "open" /\ vpc' = "closed"
  \* t_toggle_shut: open -> closed (guard: [[components.select.header_toggles]])
  \/ vpc = "open" /\ vpc' = "closed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
