---- MODULE componentspinnedpanel ----
\* Generated by `spk compile` from spec `components.pinned_panel` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"inactive", "active"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "inactive"

Next ==
  \* t_activate: inactive -> active (guard: [[components.pinned_panel.activation_range_formula]])
  \/ vpc = "inactive" /\ vpc' = "active"
  \* t_deactivate: active -> inactive (guard: [[components.pinned_panel.activation_range_formula]])
  \/ vpc = "active" /\ vpc' = "inactive"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
