//! proptest scaffolding for `components.hover` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_enter
// generator: move inside a 40 by 20 body
// predicate: the effect sets hover? to true
#[test]
fn p_enter() {
        todo_predicate!("the effect sets hover? to true");
}

// id: p_leave
// generator: global moves at -1, 41 and 21
// predicate: each adds set hover? false to the child intents
#[test]
fn p_leave() {
        todo_predicate!("each adds set hover? false to the child intents");
}

// id: p_stay
// generator: global move at 10, 10
// predicate: no hover effect is returned
#[test]
fn p_stay() {
        todo_predicate!("no hover effect is returned");
}

// id: p_mouse_out
// generator: leave with a callback
// predicate: callback intents follow the set false
#[test]
fn p_mouse_out() {
        todo_predicate!("callback intents follow the set false");
}

// id: p_button
// generator: text Add Todo with on-click
// predicate: pointer down inside returns the on-click result and up returns nothing
#[test]
fn p_button() {
        todo_predicate!("pointer down inside returns the on-click result and up returns nothing");
}

// id: p_button_visual
// generator: hover true and false
// predicate: only the hovered view contains the fill
#[test]
fn p_button_visual() {
        todo_predicate!("only the hovered view contains the fill");
}

// id: p_checkbox
// generator: checked false then true
// predicate: the effect is toggle with the checked path and applying it flips the value
#[test]
fn p_checkbox() {
        todo_predicate!("the effect is toggle with the checked path and applying it flips the value");
}

// id: p_checkbox_view
// generator: ui checkbox
// predicate: events return nothing
#[test]
fn p_checkbox_view() {
        todo_predicate!("events return nothing");
}

// id: p_touch_hover
// generator: touch pointer moves
// predicate: hover? is never set
#[test]
fn p_touch_hover() {
        todo_predicate!("hover? is never set");
}

