//! proptest scaffolding for `effect.dispatch` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_data
// generator: random effects
// predicate: JSON round-trip preserves effects with no function argument, and an update effect keeps its function by reference
#[test]
fn p_data() {
        todo_predicate!("JSON round-trip preserves effects with no function argument, and an update effect keeps its function by reference");
}

// id: p_order
// generator: random batches of sets
// predicate: final state equals sequential application
#[test]
fn p_order() {
        todo_predicate!("final state equals sequential application");
}

// id: p_update
// generator: random paths and fns
// predicate: value at path equals f(old, ...args)
#[test]
fn p_update() {
        todo_predicate!("value at path equals f(old, ...args)");
}

// id: p_set_get_delete
// generator: random paths
// predicate: set then get returns the value and delete then get returns undefined
#[test]
fn p_set_get_delete() {
        todo_predicate!("set then get returns the value and delete then get returns undefined");
}

// id: p_overloads
// generator: the three call forms
// predicate: all three apply the same effect
#[test]
fn p_overloads() {
        todo_predicate!("all three apply the same effect");
}

// id: p_unknown
// generator: batch with an unknown type
// predicate: later effects still apply and nothing throws
#[test]
fn p_unknown() {
        todo_predicate!("later effects still apply and nothing throws");
}

// id: p_compose
// generator: counter-increment
// predicate: dispatching it increments the number at the path
#[test]
fn p_compose() {
        todo_predicate!("dispatching it increments the number at the path");
}

// id: p_registry
// generator: defining an effect
// predicate: it is both dispatchable by type and callable directly
#[test]
fn p_registry() {
        todo_predicate!("it is both dispatchable by type and callable directly");
}

// id: p_captured
// generator: button click with next-todo-text hello
// predicate: state ends with a todo hello and next-todo-text empty
#[test]
fn p_captured() {
        todo_predicate!("state ends with a todo hello and next-todo-text empty");
}

// id: p_empty
// generator: empty batch
// predicate: no repaint and no handler call
#[test]
fn p_empty() {
        todo_predicate!("no repaint and no handler call");
}

// id: p_repaint
// generator: batch of N effects
// predicate: exactly one repaint is scheduled
#[test]
fn p_repaint() {
        todo_predicate!("exactly one repaint is scheduled");
}

// id: p_override
// generator: custom dispatch
// predicate: the custom function receives every effect
#[test]
fn p_override() {
        todo_predicate!("the custom function receives every effect");
}

// id: p_state_forms
// generator: plain state and cell
// predicate: both run and the cell is shared not copied
#[test]
fn p_state_forms() {
        todo_predicate!("both run and the cell is shared not copied");
}

// id: p_container
// generator: resize to 320 by 640
// predicate: context holds that size at the next render
#[test]
fn p_container() {
        todo_predicate!("context holds that size at the next render");
}

// id: p_counter_effects
// generator: num 10 and nums 0, 1, 2
// predicate: num becomes 11 and nums becomes 0, 1, 2, 0
#[test]
fn p_counter_effects() {
        todo_predicate!("num becomes 11 and nums becomes 0, 1, 2, 0");
}

// id: p_clipboard_effects
// generator: copy hello
// predicate: the backend clipboard receives hello
#[test]
fn p_clipboard_effects() {
        todo_predicate!("the backend clipboard receives hello");
}

