---- MODULE effectdispatch ----
\* Generated by `spk compile` from spec `effect.dispatch` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"quiescent", "applying", "repaint_pending"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "quiescent"

Next ==
  \* t_receive: quiescent -> applying (guard: [[effect.dispatch.empty_batch_noop]])
  \/ vpc = "quiescent" /\ vpc' = "applying"
  \* t_applied: applying -> repaint_pending (guard: [[effect.dispatch.ordered_application]])
  \/ vpc = "applying" /\ vpc' = "repaint_pending"
  \* t_painted: repaint_pending -> quiescent (guard: [[effect.dispatch.single_repaint]])
  \/ vpc = "repaint_pending" /\ vpc' = "quiescent"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
