//! proptest scaffolding for `event.bubble` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_intercept
// generator: intents including request-focus
// predicate: a request-focus intent becomes the set-focus intent from the textarea example
#[test]
fn p_intercept() {
        todo_predicate!("a request-focus intent becomes the set-focus intent from the textarea example");
}

// id: p_args
// generator: select with path and value
// predicate: the handler is called with exactly path and value
#[test]
fn p_args() {
        todo_predicate!("the handler is called with exactly path and value");
}

// id: p_pass
// generator: mixed intent lists
// predicate: non-matching intents keep identity and order
#[test]
fn p_pass() {
        todo_predicate!("non-matching intents keep identity and order");
}

// id: p_expand
// generator: handler returning two intents
// predicate: both appear in place of the original
#[test]
fn p_expand() {
        todo_predicate!("both appear in place of the original");
}

// id: p_innermost
// generator: two nested interceptors for one type
// predicate: the inner one rewrites it first and the outer never sees the original
#[test]
fn p_innermost() {
        todo_predicate!("the inner one rewrites it first and the outer never sees the original");
}

// id: p_middleware
// generator: todo-app enter key wrapper
// predicate: enter with non-empty default effects returns add-todo then set next-todo-text to empty, any other key returns the default effects
#[test]
fn p_middleware() {
        todo_predicate!("enter with non-empty default effects returns add-todo then set next-todo-text to empty, any other key returns the default effects");
}

// id: p_wrap_order
// generator: two pairs
// predicate: the first pair wraps the second
#[test]
fn p_wrap_order() {
        todo_predicate!("the first pair wraps the second");
}

// id: p_multi
// generator: on with three handlers
// predicate: equals three nested single-pair nodes
#[test]
fn p_multi() {
        todo_predicate!("equals three nested single-pair nodes");
}

// id: p_raw_bubble
// generator: handler dropping all intents
// predicate: result is empty
#[test]
fn p_raw_bubble() {
        todo_predicate!("result is empty");
}

// id: p_builtin
// generator: a row returning update of selected? with not under an on update wrapper
// predicate: the wrapper replaces it with the set-membership update and the original never reaches the dispatcher
#[test]
fn p_builtin() {
        todo_predicate!("the wrapper replaces it with the set-membership update and the original never reaches the dispatcher");
}

