---- MODULE eventmodel ----
\* Generated by `spk compile` from spec `event.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"idle", "pressed", "dragging"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "idle"

Next ==
  \* t_press: idle -> pressed (guard: [[event.model.hit_half_open]])
  \/ vpc = "idle" /\ vpc' = "pressed"
  \* t_drag: pressed -> dragging (guard: [[event.model.tap_vs_drag]])
  \/ vpc = "pressed" /\ vpc' = "dragging"
  \* t_tap: pressed -> idle (guard: [[event.model.tap_vs_drag]])
  \/ vpc = "pressed" /\ vpc' = "idle"
  \* t_release: dragging -> idle (guard: [[event.model.event_pure]])
  \/ vpc = "dragging" /\ vpc' = "idle"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
