//! proptest scaffolding for `event.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn spacer() -> impl Strategy<Value = String> {
        Just("spacer".into())
    }

    pub fn translate() -> impl Strategy<Value = String> {
        Just("translate".into())
    }

}

proptest! {
    // id: p_half_open
    // generator: spacer(20, 20) probed at 0, 19, 20 and -1
    // predicate: positions 0 and 19 hit and 20 and -1 miss
    #[test]
    fn p_half_open(v0 in spec_gen::spacer()) {
        todo_predicate!("positions 0 and 19 hit and 20 and -1 miss");
    }
    // id: p_local
    // generator: handler at translate(10, 10) probed at [15, 15]
    // predicate: handler sees [5, 5] and README returns the intent [:say-hello]
    #[test]
    fn p_local(v0 in spec_gen::translate()) {
        todo_predicate!("handler sees [5, 5] and README returns the intent [:say-hello]");
    }
}

// id: p_coords
// generator: nested translates
// predicate: handler sees the point minus the sum of offsets
#[test]
fn p_coords() {
        todo_predicate!("handler sees the point minus the sum of offsets");
}

// id: p_first_match
// generator: two overlapping nodes both with handlers
// predicate: only the later sibling's intents are returned
#[test]
fn p_first_match() {
        todo_predicate!("only the later sibling's intents are returned");
}

// id: p_down_terminal
// generator: on-mouse-down wrapping a node that also handles down
// predicate: only the outer handler fires
#[test]
fn p_down_terminal() {
        todo_predicate!("only the outer handler fires");
}

// id: p_up_descends
// generator: on-mouse-down wrapping a node that handles up
// predicate: the inner up handler fires
#[test]
fn p_up_descends() {
        todo_predicate!("the inner up handler fires");
}

// id: p_outside
// generator: points outside all nodes
// predicate: result is empty
#[test]
fn p_outside() {
        todo_predicate!("result is empty");
}

// id: p_key_concat
// generator: three siblings that each handle key-press
// predicate: the output is the three results in order
#[test]
fn p_key_concat() {
        todo_predicate!("the output is the three results in order");
}

// id: p_global_move
// generator: handlers at several offsets
// predicate: each receives its own local position and all fire
#[test]
fn p_global_move() {
        todo_predicate!("each receives its own local position and all fire");
}

// id: p_bubble
// generator: node with a counting bubble
// predicate: bubble runs exactly once per event
#[test]
fn p_bubble() {
        todo_predicate!("bubble runs exactly once per event");
}

// id: p_capability
// generator: trees with and without key handlers
// predicate: the query matches whether any descendant handles the event
#[test]
fn p_capability() {
        todo_predicate!("the query matches whether any descendant handles the event");
}

// id: p_button
// generator: down and up inside and outside
// predicate: only a down inside returns on-click
#[test]
fn p_button() {
        todo_predicate!("only a down inside returns on-click");
}

// id: p_event_pure
// generator: random events
// predicate: tree and state unchanged afterwards
#[test]
fn p_event_pure() {
        todo_predicate!("tree and state unchanged afterwards");
}

// id: p_pointer
// generator: mouse, touch and pen inputs
// predicate: all produce the same normalised shape
#[test]
fn p_pointer() {
        todo_predicate!("all produce the same normalised shape");
}

// id: p_tap
// generator: random down-up pairs
// predicate: classification matches the slop and time thresholds
#[test]
fn p_tap() {
        todo_predicate!("classification matches the slop and time thresholds");
}

