---- MODULE eventbubble ----
\* Generated by `spk compile` from spec `event.bubble` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"collecting", "intercepting", "delivered"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "collecting"

Next ==
  \* t_collect: collecting -> intercepting (guard: [[event.bubble.intercept_by_type]])
  \/ vpc = "collecting" /\ vpc' = "intercepting"
  \* t_pass: intercepting -> delivered (guard: [[event.bubble.other_intents_pass]])
  \/ vpc = "intercepting" /\ vpc' = "delivered"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
