//! proptest scaffolding for `example.todo` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_delete_x
// generator: render delete-X
// predicate: two path nodes with width 3, red, endpoints as stated, and bounds [10, 10]
#[test]
fn p_delete_x() {
        todo_predicate!("two path nodes with width 3, red, endpoints as stated, and bounds [10, 10]");
}

// id: p_item_layout
// generator: one todo
// predicate: x offsets are increasing in the stated order and the checkbox origin is [10, 4] relative to the row
#[test]
fn p_item_layout() {
        todo_predicate!("x offsets are increasing in the stated order and the checkbox origin is [10, 4] relative to the row");
}

// id: p_item_bindings
// generator: todo second with complete? false
// predicate: checkbox is unchecked and textarea text is second, and the paths end in complete? and description
#[test]
fn p_item_bindings() {
        todo_predicate!("checkbox is unchecked and textarea text is second, and the paths end in complete? and description");
}

// id: p_delete_emits
// generator: click at [8, 8] and at [20, 8] on a row
// predicate: the first returns delete with the todo path and the second does not
#[test]
fn p_delete_emits() {
        todo_predicate!("the first returns delete with the todo path and the second does not");
}

// id: p_delete
// generator: todos first, second, third and delete the first
// predicate: list becomes second, third
#[test]
fn p_delete() {
        todo_predicate!("list becomes second, third");
}

// id: p_complete
// generator: click the second checkbox
// predicate: only the second todo becomes complete
#[test]
fn p_complete() {
        todo_predicate!("only the second todo becomes complete");
}

// id: p_spacing
// generator: three todos
// predicate: row offsets differ by row height plus 5 plus the gap
#[test]
fn p_spacing() {
        todo_predicate!("row offsets differ by row height plus 5 plus the gap");
}

// id: p_toggle_render
// generator: options all, active, complete with selected active
// predicate: active is plain and the other two are gray and clickable
#[test]
fn p_toggle_render() {
        todo_predicate!("active is plain and the other two are gray and clickable");
}

// id: p_toggle
// generator: click on the active label
// predicate: effect is set selected-filter to active, and a click on the selected label returns nothing
#[test]
fn p_toggle() {
        todo_predicate!("effect is set selected-filter to active, and a click on the selected label returns nothing");
}

// id: p_filter_default
// generator: no selected-filter
// predicate: the unfiltered option is selected and three rows render
#[test]
fn p_filter_default() {
        todo_predicate!("the unfiltered option is selected and three rows render");
}

// id: p_filter_fns
// generator: todos first, second, third with third complete
// predicate: unfiltered shows 3, active shows first and second, complete shows third
#[test]
fn p_filter_fns() {
        todo_predicate!("unfiltered shows 3, active shows first and second, complete shows third");
}

// id: p_unknown_filter
// generator: selected-filter bogus
// predicate: three rows render
#[test]
fn p_unknown_filter() {
        todo_predicate!("three rows render");
}

// id: p_filtered_paths
// generator: active filter and a delete click on visible index 1
// predicate: original list becomes first, third
#[test]
fn p_filtered_paths() {
        todo_predicate!("original list becomes first, third");
}

// id: p_filtered_toggle
// generator: complete filter and unchecking the only visible todo
// predicate: third becomes open and the next render under complete shows no rows
#[test]
fn p_filtered_toggle() {
        todo_predicate!("third becomes open and the next render under complete shows no rows");
}

// id: p_add_button
// generator: next-todo-text hello
// predicate: effects are add-todo with todos path and hello, then set next-todo-text to the empty string
#[test]
fn p_add_button() {
        todo_predicate!("effects are add-todo with todos path and hello, then set next-todo-text to the empty string");
}

// id: p_add
// generator: apply add-todo hello
// predicate: list ends with description hello and complete? false
#[test]
fn p_add() {
        todo_predicate!("list ends with description hello and complete? false");
}

// id: p_enter
// generator: focused new-todo textarea and the enter key
// predicate: effects equal those of the button
#[test]
fn p_enter() {
        todo_predicate!("effects equal those of the button");
}

// id: p_enter_unfocused
// generator: unfocused textarea and enter
// predicate: no effects
#[test]
fn p_enter_unfocused() {
        todo_predicate!("no effects");
}

// id: p_other_keys
// generator: focused and the key x
// predicate: the textarea default insert-text effect is returned
#[test]
fn p_other_keys() {
        todo_predicate!("the textarea default insert-text effect is returned");
}

// id: p_new_todo_layout
// generator: initial state
// predicate: top row textarea origin is [10, 10] relative to the button's right edge and the toggle is below it
#[test]
fn p_new_todo_layout() {
        todo_predicate!("top row textarea origin is [10, 10] relative to the button's right edge and the toggle is below it");
}

// id: p_image
// generator: initial state and no DOM
// predicate: an image buffer of non-zero size is produced
#[test]
fn p_image() {
        todo_predicate!("an image buffer of non-zero size is produced");
}

// id: p_portable
// generator: the three backends
// predicate: each renders the app and routes a click to the same effect
#[test]
fn p_portable() {
        todo_predicate!("each renders the app and routes a click to the same effect");
}

// id: p_todo_touch
// generator: touch device
// predicate: each hit area is at least 44 by 44 and the visual bounds are unchanged
#[test]
fn p_todo_touch() {
        todo_predicate!("each hit area is at least 44 by 44 and the visual bounds are unchanged");
}

