//! proptest scaffolding for `example.counter` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_layout
// generator: num 10
// predicate: child 0 is the button and child 1 is the label with x offset greater than the button width
#[test]
fn p_layout() {
        todo_predicate!("child 0 is the button and child 1 is the label with x offset greater than the button width");
}

// id: p_more
// generator: num 10 and a click at the button centre
// predicate: intents equal one counter-increment with the path to num
#[test]
fn p_more() {
        todo_predicate!("intents equal one counter-increment with the path to num");
}

// id: p_increment
// generator: state num 10
// predicate: state num becomes 11
#[test]
fn p_increment() {
        todo_predicate!("state num becomes 11");
}

// id: p_stack
// generator: nums 0, 1, 2
// predicate: four rows, button first then three counters
#[test]
fn p_stack() {
        todo_predicate!("four rows, button first then three counters");
}

// id: p_independent
// generator: nums 0, 1, 2 and a click on the second more
// predicate: nums becomes 0, 2, 2
#[test]
fn p_independent() {
        todo_predicate!("nums becomes 0, 2, 2");
}

// id: p_add
// generator: nums 0, 1, 2 and a click on Add Counter
// predicate: nums becomes 0, 1, 2, 0 and a fifth row appears
#[test]
fn p_add() {
        todo_predicate!("nums becomes 0, 1, 2, 0 and a fifth row appears");
}

// id: p_label
// generator: num 10
// predicate: label text is 10
#[test]
fn p_label() {
        todo_predicate!("label text is 10");
}

// id: p_raw
// generator: atom counter and a mutating handler
// predicate: the atom is 1 after one click and one repaint occurred
#[test]
fn p_raw() {
        todo_predicate!("the atom is 1 after one click and one repaint occurred");
}

// id: p_touch
// generator: touch device
// predicate: hit area is at least 44 by 44
#[test]
fn p_touch() {
        todo_predicate!("hit area is at least 44 by 44");
}

