//! proptest scaffolding for `example.file_selector` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_row_layout
    // generator: one row
    // predicate: checkbox at origin [5, 5], then spacer, then label in order
    #[test]
    fn p_row_layout() {
        todo_predicate!("checkbox at origin [5, 5], then spacer, then label in order");
    }
}

proptest! {
    // id: p_row_default
    // generator: a row alone
    // predicate: the intent is update with the selected? path and not
    #[test]
    fn p_row_default() {
        todo_predicate!("the intent is update with the selected? path and not");
    }
}

proptest! {
    // id: p_intercept
    // generator: selected set empty then containing b
    // predicate: tapping b yields add then remove, and the boolean path is never touched
    #[test]
    fn p_intercept() {
        todo_predicate!("tapping b yields add then remove, and the boolean path is never touched");
    }
}

proptest! {
    // id: p_filter
    // generator: names a.txt, B.md, notes with filter b and filter t
    // predicate: b shows B.md and a.txt does not match, t shows a.txt and notes
    #[test]
    fn p_filter() {
        todo_predicate!("b shows B.md and a.txt does not match, t shows a.txt and notes");
    }
}

proptest! {
    // id: p_defaults
    // generator: no props besides names
    // predicate: all names shown and the selected set is empty
    #[test]
    fn p_defaults() {
        todo_predicate!("all names shown and the selected set is empty");
    }
}

proptest! {
    // id: p_membership
    // generator: selected set containing a.txt
    // predicate: only that row is checked
    #[test]
    fn p_membership() {
        todo_predicate!("only that row is checked");
    }
}

proptest! {
    // id: p_persist
    // generator: select a.txt then filter to nothing then clear
    // predicate: a.txt is still selected
    #[test]
    fn p_persist() {
        todo_predicate!("a.txt is still selected");
    }
}

proptest! {
    // id: p_result
    // generator: select two items and stop
    // predicate: the returned set equals the state set
    #[test]
    fn p_result() {
        todo_predicate!("the returned set equals the state set");
    }
}

