---- MODULE examplefileselector ----
\* Generated by `spk compile` from spec `example.file_selector` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"empty_selection", "some_selected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "empty_selection"

Next ==
  \* t_select_first: empty_selection -> some_selected (guard: [[example.file_selector.set_intercept]])
  \/ vpc = "empty_selection" /\ vpc' = "some_selected"
  \* t_deselect_last: some_selected -> empty_selection (guard: [[example.file_selector.set_intercept]])
  \/ vpc = "some_selected" /\ vpc' = "empty_selection"
  \* t_toggle_more: some_selected -> some_selected (guard: [[example.file_selector.set_intercept]])
  \/ vpc = "some_selected" /\ vpc' = "some_selected"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
