---- MODULE exampletodo ----
\* Generated by `spk compile` from spec `example.todo` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"unfiltered", "active_only", "complete_only"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unfiltered"

Next ==
  \* t_to_active: unfiltered -> active_only (guard: [[example.todo.toggle_sets_filter]])
  \/ vpc = "unfiltered" /\ vpc' = "active_only"
  \* t_to_complete: unfiltered -> complete_only (guard: [[example.todo.toggle_sets_filter]])
  \/ vpc = "unfiltered" /\ vpc' = "complete_only"
  \* t_active_to_complete: active_only -> complete_only (guard: [[example.todo.toggle_sets_filter]])
  \/ vpc = "active_only" /\ vpc' = "complete_only"
  \* t_complete_to_active: complete_only -> active_only (guard: [[example.todo.toggle_sets_filter]])
  \/ vpc = "complete_only" /\ vpc' = "active_only"
  \* t_active_to_unfiltered: active_only -> unfiltered (guard: [[example.todo.toggle_sets_filter]])
  \/ vpc = "active_only" /\ vpc' = "unfiltered"
  \* t_complete_to_unfiltered: complete_only -> unfiltered (guard: [[example.todo.toggle_sets_filter]])
  \/ vpc = "complete_only" /\ vpc' = "unfiltered"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
