//! proptest scaffolding for `example.file_selector` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_row_layout
// generator: one row
// predicate: checkbox at origin [5, 5], then spacer, then label in order
#[test]
fn p_row_layout() {
        todo_predicate!("checkbox at origin [5, 5], then spacer, then label in order");
}

// id: p_row_default
// generator: a row alone
// predicate: the intent is update with the selected? path and not
#[test]
fn p_row_default() {
        todo_predicate!("the intent is update with the selected? path and not");
}

// id: p_intercept
// generator: selected set empty then containing b
// predicate: tapping b yields add then remove, and the boolean path is never touched
#[test]
fn p_intercept() {
        todo_predicate!("tapping b yields add then remove, and the boolean path is never touched");
}

// id: p_filter
// generator: names a.txt, B.md, notes with filter b and filter t
// predicate: b shows B.md and a.txt does not match, t shows a.txt and notes
#[test]
fn p_filter() {
        todo_predicate!("b shows B.md and a.txt does not match, t shows a.txt and notes");
}

// id: p_defaults
// generator: no props besides names
// predicate: all names shown and the selected set is empty
#[test]
fn p_defaults() {
        todo_predicate!("all names shown and the selected set is empty");
}

// id: p_membership
// generator: selected set containing a.txt
// predicate: only that row is checked
#[test]
fn p_membership() {
        todo_predicate!("only that row is checked");
}

// id: p_persist
// generator: select a.txt then filter to nothing then clear
// predicate: a.txt is still selected
#[test]
fn p_persist() {
        todo_predicate!("a.txt is still selected");
}

// id: p_result
// generator: select two items and stop
// predicate: the returned set equals the state set
#[test]
fn p_result() {
        todo_predicate!("the returned set equals the state set");
}

