---- MODULE examplecounter ----
\* Generated by `spk compile` from spec `example.counter` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"empty_list", "has_counters"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "empty_list"

Next ==
  \* t_first_add: empty_list -> has_counters (guard: [[example.counter.add_appends_zero]])
  \/ vpc = "empty_list" /\ vpc' = "has_counters"
  \* t_more_add: has_counters -> has_counters (guard: [[example.counter.add_appends_zero]])
  \/ vpc = "has_counters" /\ vpc' = "has_counters"
  \* t_press_more: has_counters -> has_counters (guard: [[example.counter.increment_applies]])
  \/ vpc = "has_counters" /\ vpc' = "has_counters"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
