//! proptest scaffolding for `interop.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_plain_data
    // generator: build each node, effect and path
    // predicate: structured clone succeeds and every value is a plain type or function
    #[test]
    fn p_plain_data() {
        todo_predicate!("structured clone succeeds and every value is a plain type or function");
    }
}

proptest! {
    // id: p_string_tags
    // generator: the keyword form of ui select and the string ui slash select
    // predicate: both resolve to the same registered handler
    #[test]
    fn p_string_tags() {
        todo_predicate!("both resolve to the same registered handler");
    }
}

proptest! {
    // id: p_punctuated
    // generator: state with keys complete?, next-todo-text and dollar-num
    // predicate: select, set and update work on each
    #[test]
    fn p_punctuated() {
        todo_predicate!("select, set and update work on each");
    }
}

proptest! {
    // id: p_nil
    // generator: null, undefined and a missing key
    // predicate: all three read as nil and select returns undefined for each
    #[test]
    fn p_nil() {
        todo_predicate!("all three read as nil and select returns undefined for each");
    }
}

proptest! {
    // id: p_iterables
    // generator: children given as an array, a generator and a lazy map result
    // predicate: all three produce the same view and the output children is an array
    #[test]
    fn p_iterables() {
        todo_predicate!("all three produce the same view and the output children is an array");
    }
}

proptest! {
    // id: p_variadic
    // generator: vstack with rest args and with one array
    // predicate: the views deep-equal
    #[test]
    fn p_variadic() {
        todo_predicate!("the views deep-equal");
    }
}

proptest! {
    // id: p_free_functions
    // generator: scan the public exports
    // predicate: every export is a function, a constant or a sentinel, and none uses this
    #[test]
    fn p_free_functions() {
        todo_predicate!("every export is a function, a constant or a sentinel, and none uses this");
    }
}

proptest! {
    // id: p_functions
    // generator: an update function with rest parameters and one with default parameters
    // predicate: both are called with the same arguments
    #[test]
    fn p_functions() {
        todo_predicate!("both are called with the same arguments");
    }
}

proptest! {
    // id: p_seam
    // generator: persistent-collection ops over a 3-level state
    // predicate: update at one path works and default ops are used when none are given
    #[test]
    fn p_seam() {
        todo_predicate!("update at one path works and default ops are used when none are given");
    }
}

proptest! {
    // id: p_ops_bound
    // generator: two apps with plain and persistent ops
    // predicate: each behaves per its own ops
    #[test]
    fn p_ops_bound() {
        todo_predicate!("each behaves per its own ops");
    }
}

proptest! {
    // id: p_identity
    // generator: 5000 todos and an update to index 2
    // predicate: todo 3 is reference-equal before and after and the input is unchanged
    #[test]
    fn p_identity() {
        todo_predicate!("todo 3 is reference-equal before and after and the input is unchanged");
    }
}

proptest! {
    // id: p_tag_ns
    // generator: two keywords with the same name in different namespaces
    // predicate: the normalised tags differ and keep their namespaces
    #[test]
    fn p_tag_ns() {
        todo_predicate!("the normalised tags differ and keep their namespaces");
    }
}

proptest! {
    // id: p_no_conversion
    // generator: 1000 dispatches on 5000 todos with custom ops
    // predicate: total time is under 1000 ms and no conversion function is called
    #[test]
    fn p_no_conversion() {
        todo_predicate!("total time is under 1000 ms and no conversion function is called");
    }
}

proptest! {
    // id: p_explicit_paths
    // generator: todos with an active filter
    // predicate: the each helper gives the second visible item the path todos, filter, 1
    #[test]
    fn p_explicit_paths() {
        todo_predicate!("the each helper gives the second visible item the path todos, filter, 1");
    }
}

proptest! {
    // id: p_no_macro
    // generator: todos first, second, third with third complete and an active filter
    // predicate: deleting visible index 1 leaves first and third, and toggling visible index 0 changes only first
    #[test]
    fn p_no_macro() {
        todo_predicate!("deleting visible index 1 leaves first and third, and toggling visible index 0 changes only first");
    }
}

proptest! {
    // id: p_macro_optional
    // generator: the todo app written with and without the macro
    // predicate: both produce deep-equal views and effects
    #[test]
    fn p_macro_optional() {
        todo_predicate!("both produce deep-equal views and effects");
    }
}

proptest! {
    // id: p_esm
    // generator: import from squint and from a CLJS build
    // predicate: named imports resolve and no side effect runs at import
    #[test]
    fn p_esm() {
        todo_predicate!("named imports resolve and no side effect runs at import");
    }
}

proptest! {
    // id: p_advanced
    // generator: build the counter example with advanced optimisations
    // predicate: the click still produces the counter-increment effect
    #[test]
    fn p_advanced() {
        todo_predicate!("the click still produces the counter-increment effect");
    }
}

proptest! {
    // id: p_same_everywhere
    // generator: the same effect batch from three languages
    // predicate: the resulting states are deep-equal
    #[test]
    fn p_same_everywhere() {
        todo_predicate!("the resulting states are deep-equal");
    }
}

