//! proptest scaffolding for `interop.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_plain_data
// generator: build each node, effect and path
// predicate: structured clone succeeds and every value is a plain type or function
#[test]
fn p_plain_data() {
        todo_predicate!("structured clone succeeds and every value is a plain type or function");
}

// id: p_string_tags
// generator: the keyword form of ui select and the string ui slash select
// predicate: both resolve to the same registered handler
#[test]
fn p_string_tags() {
        todo_predicate!("both resolve to the same registered handler");
}

// id: p_punctuated
// generator: state with keys complete?, next-todo-text and dollar-num
// predicate: select, set and update work on each
#[test]
fn p_punctuated() {
        todo_predicate!("select, set and update work on each");
}

// id: p_nil
// generator: null, undefined and a missing key
// predicate: all three read as nil and select returns undefined for each
#[test]
fn p_nil() {
        todo_predicate!("all three read as nil and select returns undefined for each");
}

// id: p_iterables
// generator: children given as an array, a generator and a lazy map result
// predicate: all three produce the same view and the output children is an array
#[test]
fn p_iterables() {
        todo_predicate!("all three produce the same view and the output children is an array");
}

// id: p_variadic
// generator: vstack with rest args and with one array
// predicate: the views deep-equal
#[test]
fn p_variadic() {
        todo_predicate!("the views deep-equal");
}

// id: p_free_functions
// generator: scan the public exports
// predicate: every export is a function, a constant or a sentinel, and none uses this
#[test]
fn p_free_functions() {
        todo_predicate!("every export is a function, a constant or a sentinel, and none uses this");
}

// id: p_functions
// generator: an update function with rest parameters and one with default parameters
// predicate: both are called with the same arguments
#[test]
fn p_functions() {
        todo_predicate!("both are called with the same arguments");
}

// id: p_seam
// generator: persistent-collection ops over a 3-level state
// predicate: update at one path works and default ops are used when none are given
#[test]
fn p_seam() {
        todo_predicate!("update at one path works and default ops are used when none are given");
}

// id: p_ops_bound
// generator: two apps with plain and persistent ops
// predicate: each behaves per its own ops
#[test]
fn p_ops_bound() {
        todo_predicate!("each behaves per its own ops");
}

// id: p_identity
// generator: 5000 todos and an update to index 2
// predicate: todo 3 is reference-equal before and after and the input is unchanged
#[test]
fn p_identity() {
        todo_predicate!("todo 3 is reference-equal before and after and the input is unchanged");
}

// id: p_tag_ns
// generator: two keywords with the same name in different namespaces
// predicate: the normalised tags differ and keep their namespaces
#[test]
fn p_tag_ns() {
        todo_predicate!("the normalised tags differ and keep their namespaces");
}

// id: p_no_conversion
// generator: 1000 dispatches on 5000 todos with custom ops
// predicate: total time is under 1000 ms and no conversion function is called
#[test]
fn p_no_conversion() {
        todo_predicate!("total time is under 1000 ms and no conversion function is called");
}

// id: p_explicit_paths
// generator: todos with an active filter
// predicate: the each helper gives the second visible item the path todos, filter, 1
#[test]
fn p_explicit_paths() {
        todo_predicate!("the each helper gives the second visible item the path todos, filter, 1");
}

// id: p_no_macro
// generator: todos first, second, third with third complete and an active filter
// predicate: deleting visible index 1 leaves first and third, and toggling visible index 0 changes only first
#[test]
fn p_no_macro() {
        todo_predicate!("deleting visible index 1 leaves first and third, and toggling visible index 0 changes only first");
}

// id: p_macro_optional
// generator: the todo app written with and without the macro
// predicate: both produce deep-equal views and effects
#[test]
fn p_macro_optional() {
        todo_predicate!("both produce deep-equal views and effects");
}

// id: p_esm
// generator: import from squint and from a CLJS build
// predicate: named imports resolve and no side effect runs at import
#[test]
fn p_esm() {
        todo_predicate!("named imports resolve and no side effect runs at import");
}

// id: p_advanced
// generator: build the counter example with advanced optimisations
// predicate: the click still produces the counter-increment effect
#[test]
fn p_advanced() {
        todo_predicate!("the click still produces the counter-increment effect");
}

// id: p_same_everywhere
// generator: the same effect batch from three languages
// predicate: the resulting states are deep-equal
#[test]
fn p_same_everywhere() {
        todo_predicate!("the resulting states are deep-equal");
}

