---- MODULE interopmodel ----
\* Generated by `spk compile` from spec `interop.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"designed", "prototyped", "conformant"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "designed"

Next ==
  \* t_prototype: designed -> prototyped (guard: [[interop.model.plain_data_api]])
  \/ vpc = "designed" /\ vpc' = "prototyped"
  \* t_conform: prototyped -> conformant (guard: [[interop.model.no_macro_acceptance]])
  \/ vpc = "prototyped" /\ vpc' = "conformant"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
