//! proptest scaffolding for `membrane` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_values
    // generator: random view trees
    // predicate: JSON round-trip of a view deep-equals the original, and its type is a member of the View union
    #[test]
    fn p_values() {
        todo_predicate!("JSON round-trip of a view deep-equals the original, and its type is a member of the View union");
    }
}

proptest! {
    // id: p_pure
    // generator: random state and event
    // predicate: state is deep-equal before and after calling a handler
    #[test]
    fn p_pure() {
        todo_predicate!("state is deep-equal before and after calling a handler");
    }
}

proptest! {
    // id: p_headless
    // generator: import the core with no DOM
    // predicate: import succeeds and bounds of a label tree is computed
    #[test]
    fn p_headless() {
        todo_predicate!("import succeeds and bounds of a label tree is computed");
    }
}

proptest! {
    // id: p_no_callbacks
    // generator: scan component handlers
    // predicate: every state change appears as an effect in a returned list
    #[test]
    fn p_no_callbacks() {
        todo_predicate!("every state change appears as an effect in a returned list");
    }
}

proptest! {
    // id: p_examples
    // generator: the scenario lists of both examples
    // predicate: every scenario passes on each backend
    #[test]
    fn p_examples() {
        todo_predicate!("every scenario passes on each backend");
    }
}

proptest! {
    // id: p_typescript
    // generator: build the package
    // predicate: tsc strict passes and declarations are emitted
    #[test]
    fn p_typescript() {
        todo_predicate!("tsc strict passes and declarations are emitted");
    }
}

proptest! {
    // id: p_host
    // generator: the todo example from TypeScript, squint and ClojureScript
    // predicate: the same effects result with no conversion calls
    #[test]
    fn p_host() {
        todo_predicate!("the same effects result with no conversion calls");
    }
}

proptest! {
    // id: p_touch
    // generator: all interactive nodes
    // predicate: every hit target is at least 44 by 44
    #[test]
    fn p_touch() {
        todo_predicate!("every hit target is at least 44 by 44");
    }
}

