---- MODULE pathderivation ----
\* Generated by `spk compile` from spec `path.derivation` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"bound", "derived", "opaque"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "bound"

Next ==
  \* t_derive: bound -> derived (guard: [[path.derivation.every_binding_has_path]])
  \/ vpc = "bound" /\ vpc' = "derived"
  \* t_opaque: bound -> opaque (guard: [[path.derivation.unknown_call_opaque]])
  \/ vpc = "bound" /\ vpc' = "opaque"
  \* t_rebind: derived -> bound (guard: [[path.derivation.shadowing_uses_binding_time]])
  \/ vpc = "derived" /\ vpc' = "bound"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
