//! proptest scaffolding for `path.derivation` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_every_binding
    // generator: generated binding forms
    // predicate: every bound name has a dollar path
    #[test]
    fn p_every_binding() {
        todo_predicate!("every bound name has a dollar path");
    }
}

proptest! {
    // id: p_extract
    // generator: generated binding forms with test data
    // predicate: select by path equals the destructured value
    #[test]
    fn p_extract() {
        todo_predicate!("select by path equals the destructured value");
    }
}

proptest! {
    // id: p_update
    // generator: generated binding forms and the test value [a, 42]
    // predicate: after set the destructured name equals the test value
    #[test]
    fn p_update() {
        todo_predicate!("after set the destructured name equals the test value");
    }
}

proptest! {
    // id: p_transform
    // generator: obj a 1 and b 2 with inc
    // predicate: the selected value is one more and nothing else changes
    #[test]
    fn p_transform() {
        todo_predicate!("the selected value is one more and nothing else changes");
    }
}

proptest! {
    // id: p_compiles
    // generator: generated forms from the component_test grammar
    // predicate: derivation never throws
    #[test]
    fn p_compiles() {
        todo_predicate!("derivation never throws");
    }
}

proptest! {
    // id: p_rest
    // generator: forms with rest and rest map
    // predicate: paths cover the remaining items
    #[test]
    fn p_rest() {
        todo_predicate!("paths cover the remaining items");
    }
}

proptest! {
    // id: p_map_iter
    // generator: arg obj a 1 and b 2 iterating for [k v]
    // predicate: the three laws hold and selected values are the set 1 and 2
    #[test]
    fn p_map_iter() {
        todo_predicate!("the three laws hold and selected values are the set 1 and 2");
    }
}

proptest! {
    // id: p_key_ro
    // generator: write through a key path
    // predicate: writing is refused
    #[test]
    fn p_key_ro() {
        todo_predicate!("writing is refused");
    }
}

proptest! {
    // id: p_pairs
    // generator: arg obj a 1, b 2, c 3
    // predicate: selected values are the set a, 1, b, 2
    #[test]
    fn p_pairs() {
        todo_predicate!("selected values are the set a, 1, b, 2");
    }
}

proptest! {
    // id: p_when_let
    // generator: obj a 1 then obj nil
    // predicate: the first selects 1 and sets to obj a 2, the second yields no intents
    #[test]
    fn p_when_let() {
        todo_predicate!("the first selects 1 and sets to obj a 2, the second yields no intents");
    }
}

proptest! {
    // id: p_if_let
    // generator: obj a 1, obj nil, not-obj 1
    // predicate: then path selects 1, nil yields no then handlers, else path selects 1 on not-obj and sets to not-obj 2
    #[test]
    fn p_if_let() {
        todo_predicate!("then path selects 1, nil yields no then handlers, else path selects 1 on not-obj and sets to not-obj 2");
    }
}

proptest! {
    // id: p_shadow
    // generator: let a, then b from a, then a rebound
    // predicate: dollar b still points into the first a
    #[test]
    fn p_shadow() {
        todo_predicate!("dollar b still points into the first a");
    }
}

proptest! {
    // id: p_fn_shadow
    // generator: inner fn with parameter named like a binding
    // predicate: the inner name is not replaced
    #[test]
    fn p_fn_shadow() {
        todo_predicate!("the inner name is not replaced");
    }
}

proptest! {
    // id: p_call_table
    // generator: each known call
    // predicate: the navigator list matches the table
    #[test]
    fn p_call_table() {
        todo_predicate!("the navigator list matches the table");
    }
}

proptest! {
    // id: p_get_default
    // generator: get with default 42
    // predicate: reading an absent key gives 42
    #[test]
    fn p_get_default() {
        todo_predicate!("reading an absent key gives 42");
    }
}

proptest! {
    // id: p_assoc
    // generator: assoc onto a prop map
    // predicate: path equals the original map path
    #[test]
    fn p_assoc() {
        todo_predicate!("path equals the original map path");
    }
}

proptest! {
    // id: p_literal
    // generator: literal arguments
    // predicate: path reads the literal and refuses writes
    #[test]
    fn p_literal() {
        todo_predicate!("path reads the literal and refuses writes");
    }
}

proptest! {
    // id: p_opaque
    // generator: result of a custom function
    // predicate: value readable and path write refused
    #[test]
    fn p_opaque() {
        todo_predicate!("value readable and path write refused");
    }
}

proptest! {
    // id: p_filter_path
    // generator: todos first second third and active filter
    // predicate: the item path of the second visible todo selects second, set and delete change only the original index 1
    #[test]
    fn p_filter_path() {
        todo_predicate!("the item path of the second visible todo selects second, set and delete change only the original index 1");
    }
}

proptest! {
    // id: p_unsupported
    // generator: fori, for-kv, for-with-last
    // predicate: each raises the documented error
    #[test]
    fn p_unsupported() {
        todo_predicate!("each raises the documented error");
    }
}

proptest! {
    // id: p_unbound
    // generator: dollar name with no base
    // predicate: the symbol is left alone
    #[test]
    fn p_unbound() {
        todo_predicate!("the symbol is left alone");
    }
}

proptest! {
    // id: p_strategy
    // generator: both strategies on one vector set, with refs typed Ref<T>
    // predicate: outputs are deep-equal
    #[test]
    fn p_strategy() {
        todo_predicate!("outputs are deep-equal");
    }
}

