---- MODULE scrollytellingpin ----
\* Generated by `spk compile` from spec `scrollytelling.pin` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"unpinned", "pinned", "released"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unpinned"

Next ==
  \* pin: unpinned -> pinned (guard: [[scrollytelling.pin.spacer_reserves_height]])
  \/ vpc = "unpinned" /\ vpc' = "pinned"
  \* release: pinned -> released (guard: [[scrollytelling.pin.release_no_jump]])
  \/ vpc = "pinned" /\ vpc' = "released"
  \* release_on_focus_out: pinned -> released (guard: [[scrollytelling.pin.focus_releases_pin]])
  \/ vpc = "pinned" /\ vpc' = "released"
  \* unpin: released -> unpinned (guard: `scroll returns above the Pin's start boundary`)
  \/ vpc = "released" /\ vpc' = "unpinned"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
