//! proptest scaffolding for `scrollytelling.pin` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn scroll_sweep_within_pin_boundary() -> impl Strategy<Value = String> {
        Just("scroll_sweep_within_pin_boundary".into())
    }

    pub fn pin_with() -> impl Strategy<Value = String> {
        Just("pin_with".into())
    }

    pub fn scroll_past_pin_end_boundary() -> impl Strategy<Value = String> {
        Just("scroll_past_pin_end_boundary".into())
    }

    pub fn resize_pinned_target_then_refresh() -> impl Strategy<Value = String> {
        Just("resize_pinned_target_then_refresh".into())
    }

    pub fn two_nested_pins() -> impl Strategy<Value = String> {
        Just("two_nested_pins".into())
    }

    pub fn tab_past_last_interactive_element_in_pin() -> impl Strategy<Value = String> {
        Just("tab_past_last_interactive_element_in_pin".into())
    }

}

proptest! {
    // id: position_constant_while_pinned
    // generator: `scroll_sweep_within_pin_boundary()`
    // predicate: `viewport_position(target) is constant across every sampled frame`
    #[test]
    fn position_constant_while_pinned(v0 in spec_gen::scroll_sweep_within_pin_boundary()) {
        todo_predicate!("`viewport_position(target) is constant across every sampled frame`");
    }
    // id: spacer_matches_duration
    // generator: `pin_with(authored_duration: d)`
    // predicate: `spacer_height == d`
    #[test]
    fn spacer_matches_duration(v0 in spec_gen::pin_with()) {
        todo_predicate!("`spacer_height == d`");
    }
    // id: no_visual_jump_on_release
    // generator: `scroll_past_pin_end_boundary()`
    // predicate: `rendered_position(frame_before_release) == rendered_position(frame_after_release)`
    #[test]
    fn no_visual_jump_on_release(v0 in spec_gen::scroll_past_pin_end_boundary()) {
        todo_predicate!("`rendered_position(frame_before_release) == rendered_position(frame_after_release)`");
    }
    // id: resize_recomputes_spacer
    // generator: `resize_pinned_target_then_refresh()`
    // predicate: `spacer_height == new authored duration`
    #[test]
    fn resize_recomputes_spacer(v0 in spec_gen::resize_pinned_target_then_refresh()) {
        todo_predicate!("`spacer_height == new authored duration`");
    }
    // id: nested_priority_resolved
    // generator: `two_nested_pins(priority: unset)`
    // predicate: `stacking_order == document_order`
    #[test]
    fn nested_priority_resolved(v0 in spec_gen::two_nested_pins()) {
        todo_predicate!("`stacking_order == document_order`");
    }
    // id: tab_out_releases_focus
    // generator: `tab_past_last_interactive_element_in_pin()`
    // predicate: `check(pin_state) == released`
    #[test]
    fn tab_out_releases_focus(v0 in spec_gen::tab_past_last_interactive_element_in_pin()) {
        todo_predicate!("`check(pin_state) == released`");
    }
}

