//! proptest scaffolding for `state.paths` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_select
// generator: random nested state
// predicate: select matches direct indexing
#[test]
fn p_select() {
        todo_predicate!("select matches direct indexing");
}

// id: p_immut
// generator: random updates
// predicate: input deep-equals its prior snapshot
#[test]
fn p_immut() {
        todo_predicate!("input deep-equals its prior snapshot");
}

// id: p_share
// generator: random updates
// predicate: sibling branches are reference-equal
#[test]
fn p_share() {
        todo_predicate!("sibling branches are reference-equal");
}

// id: p_nth
// generator: maps and vectors
// predicate: map entries written back keep a map
#[test]
fn p_nth() {
        todo_predicate!("map entries written back keep a map");
}

// id: p_entry
// generator: map obj with a and b
// predicate: nth(0) of the first entry selects the key and nth(1) the value
#[test]
fn p_entry() {
        todo_predicate!("nth(0) of the first entry selects the key and nth(1) the value");
}

// id: p_filter_select
// generator: todos with mixed complete flags
// predicate: the active filter selects exactly the incomplete todos
#[test]
fn p_filter_select() {
        todo_predicate!("the active filter selects exactly the incomplete todos");
}

// id: p_filter_merge
// generator: todos first second third with third complete
// predicate: updating the second visible active todo changes original index 1
#[test]
fn p_filter_merge() {
        todo_predicate!("updating the second visible active todo changes original index 1");
}

// id: p_filter_delete
// generator: the same todos
// predicate: deleting the second visible active todo leaves first and third
#[test]
fn p_filter_delete() {
        todo_predicate!("deleting the second visible active todo leaves first and third");
}

// id: p_take_drop
// generator: random n and sequences
// predicate: take and drop address disjoint covering ranges
#[test]
fn p_take_drop() {
        todo_predicate!("take and drop address disjoint covering ranges");
}

// id: p_nil_val
// generator: nil leaves
// predicate: reads return the default
#[test]
fn p_nil_val() {
        todo_predicate!("reads return the default");
}

// id: p_keypath_list
// generator: random key lists
// predicate: equals nested keypath steps
#[test]
fn p_keypath_list() {
        todo_predicate!("equals nested keypath steps");
}

// id: p_collect
// generator: cursor and select-cursor and text paths
// predicate: the function is called with cursor, select-cursor, text in that order
#[test]
fn p_collect() {
        todo_predicate!("the function is called with cursor, select-cursor, text in that order");
}

// id: p_flatten
// generator: random nested paths
// predicate: selects equal the flat path
#[test]
fn p_flatten() {
        todo_predicate!("selects equal the flat path");
}

// id: p_rest_args
// generator: key-value lists
// predicate: round-trip is lossless
#[test]
fn p_rest_args() {
        todo_predicate!("round-trip is lossless");
}

// id: p_delete
// generator: random keys and indices
// predicate: key is absent or element is spliced
#[test]
fn p_delete() {
        todo_predicate!("key is absent or element is spliced");
}

// id: p_special
// generator: ALL, FIRST, LAST, MAP_VALS, END
// predicate: each addresses its documented location
#[test]
fn p_special() {
        todo_predicate!("each addresses its documented location");
}

// id: p_ser
// generator: random paths
// predicate: JSON round-trip is lossless for paths without a function predicate, and a keyword-style filter round-trips
#[test]
fn p_ser() {
        todo_predicate!("JSON round-trip is lossless for paths without a function predicate, and a keyword-style filter round-trips");
}

// id: p_unknown
// generator: a bogus navigator
// predicate: an error naming it is raised
#[test]
fn p_unknown() {
        todo_predicate!("an error naming it is raised");
}

