---- MODULE statepaths ----
\* Generated by `spk compile` from spec `state.paths` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"unresolved", "selected", "written"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unresolved"

Next ==
  \* t_select: unresolved -> selected (guard: [[state.paths.keypath_select]])
  \/ vpc = "unresolved" /\ vpc' = "selected"
  \* t_write: selected -> written (guard: [[state.paths.immutable_update]])
  \/ vpc = "selected" /\ vpc' = "written"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
