---- MODULE tambor ----
\* Generated by `spk compile` from spec `tambor` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"draft", "specified", "conformant"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "draft"

Next ==
  \* t_specify: draft -> specified (guard: [[tambor.views_are_values]])
  \/ vpc = "draft" /\ vpc' = "specified"
  \* t_conform: specified -> conformant (guard: [[tambor.examples_are_acceptance]])
  \/ vpc = "specified" /\ vpc' = "conformant"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
