//! proptest scaffolding for `typing.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_strict
    // generator: tsc over the library with the listed flags
    // predicate: zero diagnostics
    #[test]
    fn p_strict() {
        todo_predicate!("zero diagnostics");
    }
}

proptest! {
    // id: p_no_any
    // generator: scan the emitted declaration files
    // predicate: no exported symbol mentions any
    #[test]
    fn p_no_any() {
        todo_predicate!("no exported symbol mentions any");
    }
}

proptest! {
    // id: p_core_dom
    // generator: add document to a core file
    // predicate: tsc reports an error
    #[test]
    fn p_core_dom() {
        todo_predicate!("tsc reports an error");
    }
}

proptest! {
    // id: p_union
    // generator: a switch missing the Scale case
    // predicate: tsc reports an error on the never check
    #[test]
    fn p_union() {
        todo_predicate!("tsc reports an error on the never check");
    }
}

proptest! {
    // id: p_readonly
    // generator: assign to a node field
    // predicate: tsc reports an error
    #[test]
    fn p_readonly() {
        todo_predicate!("tsc reports an error");
    }
}

proptest! {
    // id: p_vec
    // generator: pass three numbers and a number array as a position
    // predicate: both are errors
    #[test]
    fn p_vec() {
        todo_predicate!("both are errors");
    }
}

proptest! {
    // id: p_path
    // generator: compose Path<S, A> with Path<A, B>
    // predicate: the result has type Path<S, B> and select returns B
    #[test]
    fn p_path() {
        todo_predicate!("the result has type Path<S, B> and select returns B");
    }
}

proptest! {
    // id: p_mismatch
    // generator: set a string through Path<S, number>
    // predicate: tsc reports an error
    #[test]
    fn p_mismatch() {
        todo_predicate!("tsc reports an error");
    }
}

proptest! {
    // id: p_navigators
    // generator: each navigator on a todos array state
    // predicate: the inferred types match the documented table
    #[test]
    fn p_navigators() {
        todo_predicate!("the inferred types match the documented table");
    }
}

proptest! {
    // id: p_dollar
    // generator: a component with props num and nums
    // predicate: the props type has dollar-num as Path<Root, number> and dollar-nums as Path<Root, number[]>, and omitting one errors
    #[test]
    fn p_dollar() {
        todo_predicate!("the props type has dollar-num as Path<Root, number> and dollar-nums as Path<Root, number[]>, and omitting one errors");
    }
}

proptest! {
    // id: p_defaults
    // generator: selected-filter with a default
    // predicate: the call site may omit it and the body sees a defined value
    #[test]
    fn p_defaults() {
        todo_predicate!("the call site may omit it and the body sees a defined value");
    }
}

proptest! {
    // id: p_context
    // generator: augment context with a theme field
    // predicate: the field is typed in every component
    #[test]
    fn p_context() {
        todo_predicate!("the field is typed in every component");
    }
}

proptest! {
    // id: p_effect_union
    // generator: register a custom add-todo effect
    // predicate: it appears in the union with its argument types
    #[test]
    fn p_effect_union() {
        todo_predicate!("it appears in the union with its argument types");
    }
}

proptest! {
    // id: p_dispatch
    // generator: dispatch an unknown type and a wrong argument
    // predicate: both are compile errors
    #[test]
    fn p_dispatch() {
        todo_predicate!("both are compile errors");
    }
}

proptest! {
    // id: p_handlers
    // generator: a mouse-down handler with the wrong parameter
    // predicate: tsc reports an error
    #[test]
    fn p_handlers() {
        todo_predicate!("tsc reports an error");
    }
}

proptest! {
    // id: p_intercept
    // generator: on select with the wrong parameter types
    // predicate: tsc reports an error
    #[test]
    fn p_intercept() {
        todo_predicate!("tsc reports an error");
    }
}

proptest! {
    // id: p_generic
    // generator: call counter with no num and with an extra prop
    // predicate: both are compile errors
    #[test]
    fn p_generic() {
        todo_predicate!("both are compile errors");
    }
}

proptest! {
    // id: p_erased
    // generator: strip annotations and rerun the behaviour suite
    // predicate: results are identical
    #[test]
    fn p_erased() {
        todo_predicate!("results are identical");
    }
}

proptest! {
    // id: p_type_tests
    // generator: break a type on purpose
    // predicate: the CI type-test job fails
    #[test]
    fn p_type_tests() {
        todo_predicate!("the CI type-test job fails");
    }
}

proptest! {
    // id: p_esm
    // generator: import one component into a bundler
    // predicate: unused components are absent from the bundle
    #[test]
    fn p_esm() {
        todo_predicate!("unused components are absent from the bundle");
    }
}

proptest! {
    // id: p_serialisable
    // generator: add-todo and update with a function
    // predicate: add-todo round-trips through JSON and the update effect is marked function-bearing
    #[test]
    fn p_serialisable() {
        todo_predicate!("add-todo round-trips through JSON and the update effect is marked function-bearing");
    }
}

