---- MODULE typingmodel ----
\* Generated by `spk compile` from spec `typing.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"untyped", "typed", "verified"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "untyped"

Next ==
  \* t_type: untyped -> typed (guard: [[typing.model.strict_compiler]])
  \/ vpc = "untyped" /\ vpc' = "typed"
  \* t_verify: typed -> verified (guard: [[typing.model.type_tests_in_ci]])
  \/ vpc = "typed" /\ vpc' = "verified"
  \* t_regress: verified -> untyped (guard: [[typing.model.types_erased]])
  \/ vpc = "verified" /\ vpc' = "untyped"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
