---- MODULE uimobile ----
\* Generated by `spk compile` from spec `ui.mobile` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"portrait", "landscape", "keyboard_open"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "portrait"

Next ==
  \* t_rotate: portrait -> landscape (guard: [[ui.mobile.orientation_supported]])
  \/ vpc = "portrait" /\ vpc' = "landscape"
  \* t_rotate_back: landscape -> portrait (guard: [[ui.mobile.orientation_supported]])
  \/ vpc = "landscape" /\ vpc' = "portrait"
  \* t_keyboard_open: portrait -> keyboard_open (guard: [[ui.mobile.keyboard_avoidance]])
  \/ vpc = "portrait" /\ vpc' = "keyboard_open"
  \* t_keyboard_close: keyboard_open -> portrait (guard: [[ui.mobile.viewport_responsive]])
  \/ vpc = "keyboard_open" /\ vpc' = "portrait"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
