//! proptest scaffolding for `ui.mobile` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p_touch_map
// generator: a tap on the more button
// predicate: the same effect as a mouse click is returned
#[test]
fn p_touch_map() {
        todo_predicate!("the same effect as a mouse click is returned");
}

// id: p_slop
// generator: todo delete X with a touch 15 px right of its centre
// predicate: the delete effect fires while drawn bounds stay 10 by 10
#[test]
fn p_slop() {
        todo_predicate!("the delete effect fires while drawn bounds stay 10 by 10");
}

// id: p_overlap
// generator: two 20 px targets 10 px apart
// predicate: a touch between them picks the nearer centre
#[test]
fn p_overlap() {
        todo_predicate!("a touch between them picks the nearer centre");
}

// id: p_reflow
// generator: widths 320 to 1024
// predicate: layout is valid at every width
#[test]
fn p_reflow() {
        todo_predicate!("layout is valid at every width");
}

// id: p_overflow
// generator: width 320 and the todo app
// predicate: no node extends past the viewport
#[test]
fn p_overflow() {
        todo_predicate!("no node extends past the viewport");
}

// id: p_thumb
// generator: primary actions
// predicate: y of each is in the bottom third
#[test]
fn p_thumb() {
        todo_predicate!("y of each is in the bottom third");
}

// id: p_gestures
// generator: scripted gestures
// predicate: each gesture emits its named intent
#[test]
fn p_gestures() {
        todo_predicate!("each gesture emits its named intent");
}

// id: p_keyboard_bridge
// generator: focus then input events
// predicate: insert, backspace and enter effects are emitted
#[test]
fn p_keyboard_bridge() {
        todo_predicate!("insert, backspace and enter effects are emitted");
}

// id: p_avoid
// generator: random focus positions
// predicate: the focused textarea is inside the visible area
#[test]
fn p_avoid() {
        todo_predicate!("the focused textarea is inside the visible area");
}

// id: p_handles
// generator: long-press on a word
// predicate: the word is selected and two handles exist
#[test]
fn p_handles() {
        todo_predicate!("the word is selected and two handles exist");
}

// id: p_rotate
// generator: rotation during use
// predicate: state is deep-equal after rotation
#[test]
fn p_rotate() {
        todo_predicate!("state is deep-equal after rotation");
}

// id: p_motion
// generator: the media query on
// predicate: no momentum frames are scheduled
#[test]
fn p_motion() {
        todo_predicate!("no momentum frames are scheduled");
}

// id: p_theme
// generator: both color schemes
// predicate: tokens resolve in each
#[test]
fn p_theme() {
        todo_predicate!("tokens resolve in each");
}

// id: p_haptics
// generator: vibrate present and absent
// predicate: no error either way
#[test]
fn p_haptics() {
        todo_predicate!("no error either way");
}

// id: p_no_hover
// generator: touch moves over a button
// predicate: hover? is never set
#[test]
fn p_no_hover() {
        todo_predicate!("hover? is never set");
}

