//! proptest scaffolding for `view.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_frozen
    // generator: random nodes
    // predicate: assigning to a node throws or is ignored
    #[test]
    fn p_frozen() {
        todo_predicate!("assigning to a node throws or is ignored");
    }
}

proptest! {
    // id: p_bounds
    // generator: random trees
    // predicate: all bounds are finite and non-negative, and bounds(nil) equals [0, 0]
    #[test]
    fn p_bounds() {
        todo_predicate!("all bounds are finite and non-negative, and bounds(nil) equals [0, 0]");
    }
}

proptest! {
    // id: p_container
    // generator: children with random origins and sizes
    // predicate: bounds equal the max of origin plus size
    #[test]
    fn p_container() {
        todo_predicate!("bounds equal the max of origin plus size");
    }
}

proptest! {
    // id: p_translate
    // generator: random offsets
    // predicate: origin equals [x, y] and bounds equal child bounds
    #[test]
    fn p_translate() {
        todo_predicate!("origin equals [x, y] and bounds equal child bounds");
    }
}

proptest! {
    // id: p_origin
    // generator: non-offset nodes
    // predicate: origin equals [0, 0]
    #[test]
    fn p_origin() {
        todo_predicate!("origin equals [0, 0]");
    }
}

proptest! {
    // id: p_group
    // generator: vectors with nil members
    // predicate: children are the elements and nil members measure [0, 0]
    #[test]
    fn p_group() {
        todo_predicate!("children are the elements and nil members measure [0, 0]");
    }
}

proptest! {
    // id: p_roundtrip
    // generator: random trees
    // predicate: makeNode(n, children(n)) deep-equals n
    #[test]
    fn p_roundtrip() {
        todo_predicate!("makeNode(n, children(n)) deep-equals n");
    }
}

proptest! {
    // id: p_measure
    // generator: stub measure fn
    // predicate: label bounds equal the stub output
    #[test]
    fn p_measure() {
        todo_predicate!("label bounds equal the stub output");
    }
}

proptest! {
    // id: p_button_bounds
    // generator: random label text
    // predicate: bounds equal label bounds plus [12, 12]
    #[test]
    fn p_button_bounds() {
        todo_predicate!("bounds equal label bounds plus [12, 12]");
    }
}

proptest! {
    // id: p_set_size
    // generator: wrappers with one and two children
    // predicate: one child succeeds and two children throws
    #[test]
    fn p_set_size() {
        todo_predicate!("one child succeeds and two children throws");
    }
}

proptest! {
    // id: p_checkbox_geometry
    // generator: checked true and false
    // predicate: bounds are 12 by 12 in both states and only the checked view has the check path
    #[test]
    fn p_checkbox_geometry() {
        todo_predicate!("bounds are 12 by 12 in both states and only the checked view has the check path");
    }
}

proptest! {
    // id: p_style
    // generator: random colors and styles
    // predicate: bounds equal the unwrapped bounds
    #[test]
    fn p_style() {
        todo_predicate!("bounds equal the unwrapped bounds");
    }
}

