//! proptest scaffolding for `view.layout` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_vstack
    // generator: random child sizes
    // predicate: children are ordered with no vertical overlap, and sizes 10, 20, 30 give offsets 0, 11 and 32
    #[test]
    fn p_vstack() {
        todo_predicate!("children are ordered with no vertical overlap, and sizes 10, 20, 30 give offsets 0, 11 and 32");
    }
}

proptest! {
    // id: p_hstack
    // generator: random child sizes
    // predicate: no horizontal overlap, and widths 10, 20 give offsets 0 and 11
    #[test]
    fn p_hstack() {
        todo_predicate!("no horizontal overlap, and widths 10, 20 give offsets 0 and 11");
    }
}

proptest! {
    // id: p_empty
    // generator: no children
    // predicate: result is nil and nothing throws
    #[test]
    fn p_empty() {
        todo_predicate!("result is nil and nothing throws");
    }
}

proptest! {
    // id: p_spacer
    // generator: random spacer sizes
    // predicate: spacer(0, 5) between two rows pushes the second row down by 5 plus gaps
    #[test]
    fn p_spacer() {
        todo_predicate!("spacer(0, 5) between two rows pushes the second row down by 5 plus gaps");
    }
}

proptest! {
    // id: p_center
    // generator: random sizes
    // predicate: offsets equal half the free space
    #[test]
    fn p_center() {
        todo_predicate!("offsets equal half the free space");
    }
}

proptest! {
    // id: p_table
    // generator: random tables
    // predicate: columns and rows align
    #[test]
    fn p_table() {
        todo_predicate!("columns and rows align");
    }
}

proptest! {
    // id: p_stretch
    // generator: random container sizes
    // predicate: no stretch node remains after resolution
    #[test]
    fn p_stretch() {
        todo_predicate!("no stretch node remains after resolution");
    }
}

proptest! {
    // id: p_layout_pure
    // generator: headless runtime
    // predicate: layout runs with no DOM
    #[test]
    fn p_layout_pure() {
        todo_predicate!("layout runs with no DOM");
    }
}

proptest! {
    // id: p_reflow
    // generator: widths 320 then 768
    // predicate: the second layout differs and is not a cached copy of the first
    #[test]
    fn p_reflow() {
        todo_predicate!("the second layout differs and is not a cached copy of the first");
    }
}

