---- MODULE viewlayout ----
\* Generated by `spk compile` from spec `view.layout` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"unplaced", "placed", "stretched"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "unplaced"

Next ==
  \* t_place: unplaced -> placed (guard: [[view.layout.vstack_offsets]])
  \/ vpc = "unplaced" /\ vpc' = "placed"
  \* t_stretch: placed -> stretched (guard: [[view.layout.stretch_resolved]])
  \/ vpc = "placed" /\ vpc' = "stretched"
  \* t_reflow: stretched -> placed (guard: [[view.layout.layout_reflows]])
  \/ vpc = "stretched" /\ vpc' = "placed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
