---- MODULE viewmodel ----
\* Generated by `spk compile` from spec `view.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"constructed", "measured", "drawn"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "constructed"

Next ==
  \* t_measure: constructed -> measured (guard: [[view.model.bounds_total]])
  \/ vpc = "constructed" /\ vpc' = "measured"
  \* t_draw: measured -> drawn (guard: [[view.model.immutable_nodes]])
  \/ vpc = "measured" /\ vpc' = "drawn"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
